spring:
  profiles: dev
  application:
    name: service-010
  devtools:
    add-properties: false
  kafka:
    producer:
      acks: 1
      retries: 0
      client-id: kafka-producer-010
      batch-size: 16348
      buffer-memory: 33554432
      bootstrap-servers: node101:9092, node102:9092, node103:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
        ms: 0
server:
  port: 12010
  servlet:
    context-path: /010
logging:
  level:
    root: info
  file:
    name: /opt/logs/spring/boot/010/dev/info.log
  pattern:
    file: '%m'
    #console: '%m'
---
spring:
  profiles: sit
  application:
    name: service-010
  devtools:
    add-properties: false
  kafka:
    producer:
      acks: 1
      retries: 0
      client-id: kafka-producer-010
      batch-size: 16348
      buffer-memory: 33554432
      bootstrap-servers: node101:9092, node102:9092, node103:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
        ms: 0
server:
  port: 12010
  servlet:
    context-path: /010
logging:
  level:
    root: info
  file:
    name: /opt/logs/spring/boot/010/sit/info.log
  pattern:
    file: '%m'
    #console: '%m'
---
spring:
  profiles: uat
  application:
    name: service-010
  devtools:
    add-properties: false
  kafka:
    producer:
      acks: 1
      retries: 0
      client-id: kafka-producer-010
      batch-size: 16348
      buffer-memory: 33554432
      bootstrap-servers: node101:9092, node102:9092, node103:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
        ms: 0
server:
  port: 12010
  servlet:
    context-path: /010
logging:
  level:
    root: info
  file:
    name: /opt/logs/spring/boot/010/uat/info.log
  pattern:
    file: '%m'
    #console: '%m'
---
