spring:
  profiles: dev
  application:
    name: service-004
server:
  port: 12004
  servlet:
    context-path: /client
eureka:
  instance:
    hostname: redhat
    appname: service-004
  client:
    service-url:
      defaultZone: http://localhost:12003/eureka
---
spring:
  profiles: sit
  application:
    name: service-004
server:
  port: 12005
  servlet:
    context-path: /client
eureka:
  instance:
    hostname: redhat
    appname: service-004
  client:
    service-url:
      defaultZone: http://node101:12003/eureka
---
spring:
  profiles: uat
  application:
    name: service-004
server:
  port: 12006
  servlet:
    context-path: /client
eureka:
  instance:
    hostname: redhat
    appname: service-004
  client:
    service-url:
      defaultZone: http://node101:12003/eureka
---
#spring:
#  profiles:
#    active: uat