spring:
  profiles: dev
  application:
    name: service-003
server:
  port: 12003
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:12003/eureka
---
spring:
  profiles: sit
  application:
    name: service-003
server:
  port: 12003
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://node101:12003/eureka
---
spring:
  profiles: uat
  application:
    name: service-003
server:
  port: 12003
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://node101:12003/eureka
---
#spring:
#  profiles:
#    active: dev