server:
  port: 12012
#  servlet:
#    context-path: /gateway
spring:
  application:
    name: service-012
  config:
    activate:
      on-profile: dev
  cloud:
    zookeeper:
      prefix: sfb-service
      discovery:
        instance-host: 192.168.100.100
      connect-string: node101:2181
    gateway:
      routes:
        - id: service-013
          order: 1001
          uri: http://192.168.100.100:12013
          predicates:
            - Path=/service/service-013/msg
        - id: service-013
          order: 1002
          uri: http://192.168.100.100:22013
          predicates:
            - Path=/service/service-013/msg
        - id: service-013
          order: 1003
          uri: http://192.168.100.100:32013
          predicates:
            - Path=/service/service-013/msg
#eureka:
#  instance:
#    hostname: redhat
#    appname: service-012
#  client:
#    service-url:
#      defaultZone: http://localhost:12003/eureka
#http://localhost:12006/service/service-004/msg