server:
  port: 12012
#  servlet:
#    context-path: /gateway
spring:
  application:
    name: service-012
  cloud:
    gateway:
      routes:
        - id: service-013
          order: 1001
          uri: http://localhost:12013
          predicates:
            - Path=/service/service-013/msg
    zookeeper:
      connect-string: node101:2181
  config:
    activate:
      on-profile: dev
#eureka:
#  instance:
#    hostname: redhat
#    appname: service-012
#  client:
#    service-url:
#      defaultZone: http://localhost:12003/eureka
#http://localhost:12006/service/service-004/msg