server:
  port: 12014
  servlet:
    context-path: /load
spring:
  application:
    name: service-014
  config:
    activate:
      on-profile: dev
  cloud:
    zookeeper:
      prefix: sfb-service
      connect-string: node101:2181
      discovery:
        instance-host: 192.168.100.100
      dependencies:
        service-013:
          path: /service-013
          loadBalancerType: RANDOM
          contentTypeTemplate: application/vnd.service-013.$version+json
          version: v1
          required: true
    loadbalancer:
      zone: node101:2181
