server:
  port: 12014
  servlet:
    context-path: /load
spring:
  application:
    name: service-014
  cloud:
    zookeeper:
      prefix: sfb-service
      discovery:
        instance-host: 192.168.100.100
      connect-string: node101:2181
  config:
    activate:
      on-profile: dev
#spring.cloud.loadbalancer