spring:
  profiles: dev
  application:
    name: service-001
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhujiejun/spring-boot-config.git
          basedir: /opt/data/spring/boot/001/conf
          username: zhujiejun
          password: clh2012woaini
          refresh-rate: 5
          force-pull: true
          clone-on-start: true
          #search-paths:
  devtools:
    add-properties: false
server:
  port: 12001
logging:
  level:
    root: warn
  file:
    name: /opt/logs/spring/boot/001/info.log
  pattern:
    file: '%m'
    #console: '%m'
---
spring:
  profiles: sit
  application:
    name: service-001
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhujiejun/spring-boot-config.git
          basedir: /opt/jars/service-001-conf-1.0.0
          username: zhujiejun
          password: clh2012woaini
          refresh-rate: 5
          force-pull: true
          clone-on-start: true
  devtools:
    add-properties: false
server:
  port: 12001
---
spring:
  profiles: uat
  application:
    name: service-001
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhujiejun/spring-boot-config.git
          basedir: /opt/jars/service-001-conf-1.0.0
          username: zhujiejun
          password: clh2012woaini
          refresh-rate: 5
          force-pull: true
          clone-on-start: true
  devtools:
    add-properties: false
server:
  port: 12001
---
