spring:
  profiles: dev
  application:
    name: service-002
server:
  port: 12002
---
spring:
  profiles: dev
  application:
    name: service-002
server:
  port: 12002
---
spring:
  profiles: dev
  application:
    name: service-002
server:
  port: 12002
---