spring:
  profiles: dev
  application:
    name: service-002
  cloud:
    config:
      uri: http://node101:12001
#spring.cloud.config
server:
  port: 12002
---
spring:
  profiles: sit
  application:
    name: service-002
server:
  port: 12002
---
spring:
  profiles: uat
  application:
    name: service-002
server:
  port: 12002
---