server:
  port: 12013
  servlet:
    context-path: /service
spring:
  application:
    name: service-013
  config:
    activate:
      on-profile: dev
  cloud:
    zookeeper:
      prefix: sfb-service
      connect-string: node101:2181
      discovery:
        instance-host: 192.168.100.100
